/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaDePresentacion;

import capaDeNegocios.AdministrarBebidas;
import capaDeNegocios.AdministrarIngredientes;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Francisco
 */
public class VentanaPrincipalSistemaUsuarioSimple extends javax.swing.JFrame {

    public static int alto;
    public static int ancho;
    AdministrarIngredientes admin = new AdministrarIngredientes();
    AdministrarBebidas admon = new AdministrarBebidas();


    /**
     * Creates new form VentanaPrincipalSistema
     */
    public VentanaPrincipalSistemaUsuarioSimple() {
        initComponents();
        this.setLocationRelativeTo(null);
        tamaño();
         this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
    }

    public void Centrate(Container frame) {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = frame.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        frame.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
    }

    public void tamaño() {
        // TODO code application logic here
        //Obtiene el tamaño de la pantalla
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        //obtiene la resolucion de la pantalla en PPP (Puntos por pulgada)
        int sr = Toolkit.getDefaultToolkit().getScreenResolution();
        //muestra la informacion por la consola de java
        // System.out.println("Tamaño de pantalla: " + d.width + "x" + d.height + ", definición: " + sr + " ppp");
        VentanaPrincipalSistema.ancho = d.width;
        VentanaPrincipalSistema.alto = d.height;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonInventario = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonVender = new javax.swing.JButton();
        botonCerrarSesion = new javax.swing.JButton();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PUNTO DE VENTA Y CONTROL DE INVENTARIO SPICY FACTORY");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonInventario.png"))); // NOI18N
        botonInventario.setBorder(null);
        botonInventario.setBorderPainted(false);
        botonInventario.setContentAreaFilled(false);
        botonInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(botonInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, 310));

        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonSalir.png"))); // NOI18N
        botonSalir.setBorder(null);
        botonSalir.setBorderPainted(false);
        botonSalir.setContentAreaFilled(false);
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 710, 180, -1));

        botonVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boton Vender.png"))); // NOI18N
        botonVender.setBorder(null);
        botonVender.setBorderPainted(false);
        botonVender.setContentAreaFilled(false);
        botonVender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVenderActionPerformed(evt);
            }
        });
        getContentPane().add(botonVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        botonCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonCerrarSesion.png"))); // NOI18N
        botonCerrarSesion.setBorder(null);
        botonCerrarSesion.setBorderPainted(false);
        botonCerrarSesion.setContentAreaFilled(false);
        botonCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(botonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 640, -1, -1));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo Principal.png"))); // NOI18N
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "¿ Esta seguro que desea salir del sistema ?", "SALIR DEL SISTEMA",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "¿ Esta seguro que desea cerrar sesión ?", "CERRAR SESION",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            this.dispose();
            VentanaInicioSesion ventanaInicioSesion;
            ventanaInicioSesion = new VentanaInicioSesion();
            ventanaInicioSesion.setVisible(true);
        }
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    private void botonVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVenderActionPerformed
        ResultSet rs;
        ResultSet rs2;
        rs = admin.avisoIngredienteBajo();
        rs2 = admon.avisoBebidaBaja();
        VentanaVentaUsuarioSimple vv;
        vv = new VentanaVentaUsuarioSimple();
        VentanaAviso va;
        va = new VentanaAviso();
        try {
            if (rs.next() || rs2.next()) {

                vv.setVisible(true);
                va.setVisible(true);
            } else {
                vv.setVisible(true);

            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPrincipalSistema.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_botonVenderActionPerformed

    private void botonInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInventarioActionPerformed
        VentanaInventarioUsuarioSimple voi;
        voi = new VentanaInventarioUsuarioSimple();
        voi.setVisible(true);
  
    }//GEN-LAST:event_botonInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new VentanaPrincipalSistemaUsuarioSimple().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonInventario;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonVender;
    private javax.swing.JLabel labelFondo;
    // End of variables declaration//GEN-END:variables
}
