/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaDePresentacion;

import capaDeNegocios.IFacade;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;

/**
 *
 * @author Francisco
 */
public class VentanaReporteCompras extends javax.swing.JFrame {

    IFacade facade = new IFacade();
    DateFormat format = new SimpleDateFormat("yyyy-MM--dd");
    JFormattedTextField dateTextField = new JFormattedTextField(format);

    /**
     * Creates new form VentanaReporteIngrediente
     */
    public VentanaReporteCompras() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    private void validacionSoloNumeros(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        String txt = "/,+*¨{.}[]_!#$%&*()=?¡áéíóú´|°¬;:asdfghjklqwertyuiopzxcvbnmñASDFGHJKLQWERTYUIOPZXCVBNMÑ";
        String caracter = String.valueOf(c);
        if (txt.contains(caracter)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Signo no permitido, Solo números");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        botonAceptar = new javax.swing.JButton();
        campoFechaInicio = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonReportePorFecha = new javax.swing.JButton();
        botonReportePorFechas = new javax.swing.JButton();
        botonReporteTodasCompras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campoFechaFin = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENTANA REPORTE COMPRAS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        botonAceptar.setBorderPainted(false);
        botonAceptar.setContentAreaFilled(false);
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 120, 70));

        campoFechaInicio.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        try {
            campoFechaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoFechaInicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoFechaInicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        campoFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFechaInicioActionPerformed(evt);
            }
        });
        campoFechaInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoFechaInicioKeyTyped(evt);
            }
        });
        getContentPane().add(campoFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 160, 31));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("FECHA DESDE:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("año/mes/día");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 100, -1));

        botonReportePorFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonReportePorDia.png"))); // NOI18N
        botonReportePorFecha.setBorderPainted(false);
        botonReportePorFecha.setContentAreaFilled(false);
        botonReportePorFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonReportePorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReportePorFechaActionPerformed(evt);
            }
        });
        getContentPane().add(botonReportePorFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 260, 100));

        botonReportePorFechas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonReportePorFechas.png"))); // NOI18N
        botonReportePorFechas.setBorderPainted(false);
        botonReportePorFechas.setContentAreaFilled(false);
        botonReportePorFechas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonReportePorFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReportePorFechasActionPerformed(evt);
            }
        });
        getContentPane().add(botonReportePorFechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 280, 110));

        botonReporteTodasCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonReporteTodasLasCompras.png"))); // NOI18N
        botonReporteTodasCompras.setBorderPainted(false);
        botonReporteTodasCompras.setContentAreaFilled(false);
        botonReporteTodasCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonReporteTodasCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteTodasComprasActionPerformed(evt);
            }
        });
        getContentPane().add(botonReporteTodasCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 340, 100));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("FECHA HASTA:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        campoFechaFin.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        try {
            campoFechaFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoFechaFin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoFechaFin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        campoFechaFin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoFechaFinKeyTyped(evt);
            }
        });
        getContentPane().add(campoFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 160, 31));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("año/mes/día");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 100, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoReportes.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        this.dispose();

    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonReportePorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReportePorFechaActionPerformed
        if (campoFechaInicio.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "VERIFIQUE NO EXISTAN CAMPOS VACIOS");
        } else {
            try {
                String ruta = "src/reportes/reporteComprasTotalesPorFecha.jasper";
                Map parametros = new HashMap();
                parametros.put("FECHAV", campoFechaInicio.getText());
                JasperPrint reporte = JasperFillManager.fillReport(ruta, parametros, facade.GetConnection());
                JasperExportManager.exportReportToPdfFile(reporte, "src/reportes/reporteComprasTotalesPorFecha.pdf");
//            JasperViewer ventana = new JasperViewer(reporte, false);
//            ventana.setTitle("REPORTE DE INGREDIENTES");
//            ventana.setVisible(true);
//            JOptionPane.showMessageDialog(null, "Reporte Generado en formato PDF");
                try {
                    File path = new File("src/reportes/reporteComprasTotalesPorFecha.pdf");
                    Desktop.getDesktop().open(path);
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Inserte una Fecha Desde");
            }
        }
    }//GEN-LAST:event_botonReportePorFechaActionPerformed

    private void botonReportePorFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReportePorFechasActionPerformed
        if (campoFechaInicio.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "VERIFIQUE NO EXISTAN CAMPOS VACIOS");
        } else {
            try {
                String ruta = "src/reportes/reporteComprasPorFecha.jasper";
                Map parametros = new HashMap();
                parametros.put("FECHADESDE", campoFechaInicio.getText());
                parametros.put("FECHAHASTA", campoFechaFin.getText());
                JasperPrint reporte = JasperFillManager.fillReport(ruta, parametros, facade.GetConnection());
                JasperExportManager.exportReportToPdfFile(reporte, "src/reportes/reporteComprasPorFecha.pdf");
//            JasperViewer ventana = new JasperViewer(reporte, false);
//            ventana.setTitle("REPORTE DE INGREDIENTES");
//            ventana.setVisible(true);
//            JOptionPane.showMessageDialog(null, "Reporte Generado en formato PDF");
                try {
                    File path = new File("src/reportes/reporteComprasPorFecha.pdf");
                    Desktop.getDesktop().open(path);
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ingrese una Fecha Desde y una Fecha Hasta");
            }
        }
    }//GEN-LAST:event_botonReportePorFechasActionPerformed

    private void botonReporteTodasComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteTodasComprasActionPerformed
        try {
            String ruta = "src/reportes/reporteComprasTotales.jasper";
            Map parametros = new HashMap();
            JasperPrint reporte = JasperFillManager.fillReport(ruta, parametros, facade.GetConnection());
            JasperExportManager.exportReportToPdfFile(reporte, "src/reportes/reporteComprasTotales.pdf");
//            JasperViewer ventana = new JasperViewer(reporte, false);
//            ventana.setTitle("REPORTE DE INGREDIENTES");
//            ventana.setVisible(true);
//            JOptionPane.showMessageDialog(null, "Reporte Generado en formato PDF");
            try {
                File path = new File("src/reportes/reporteComprasTotales.pdf");
                Desktop.getDesktop().open(path);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo generar reporte");
        }

    }//GEN-LAST:event_botonReporteTodasComprasActionPerformed

    private void campoFechaInicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoFechaInicioKeyTyped
        validacionSoloNumeros(evt);
    }//GEN-LAST:event_campoFechaInicioKeyTyped

    private void campoFechaFinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoFechaFinKeyTyped
        validacionSoloNumeros(evt);
    }//GEN-LAST:event_campoFechaFinKeyTyped

    private void campoFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFechaInicioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonReportePorFecha;
    private javax.swing.JButton botonReportePorFechas;
    private javax.swing.JButton botonReporteTodasCompras;
    private javax.swing.JFormattedTextField campoFechaFin;
    private javax.swing.JFormattedTextField campoFechaInicio;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
