/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package capaDePresentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author Francisco
 */
public class VentanaInventarioUsuarioSimple extends javax.swing.JFrame {

    /**
     * Creates new form VentanaReportes
     */
    public VentanaInventarioUsuarioSimple() {
        initComponents();
        this.setLocationRelativeTo(null);
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonIngredientesInventario = new javax.swing.JButton();
        botonBebidasInventario = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opción Inventario");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonIngredientesInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonIngredientesInventario.png"))); // NOI18N
        botonIngredientesInventario.setBorder(null);
        botonIngredientesInventario.setBorderPainted(false);
        botonIngredientesInventario.setContentAreaFilled(false);
        botonIngredientesInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonIngredientesInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngredientesInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(botonIngredientesInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        botonBebidasInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonBebidasInventario.png"))); // NOI18N
        botonBebidasInventario.setBorder(null);
        botonBebidasInventario.setBorderPainted(false);
        botonBebidasInventario.setContentAreaFilled(false);
        botonBebidasInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBebidasInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBebidasInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(botonBebidasInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        botonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        botonRegresar.setBorder(null);
        botonRegresar.setBorderPainted(false);
        botonRegresar.setContentAreaFilled(false);
        botonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoOpcionInventario.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIngredientesInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngredientesInventarioActionPerformed
        VentanaInventarioIngredienteUsuarioSimple viiu;
        viiu = new VentanaInventarioIngredienteUsuarioSimple();
        viiu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonIngredientesInventarioActionPerformed

    private void botonBebidasInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBebidasInventarioActionPerformed
        VentanaInventarioBebidaUsuarioSimple vibus;
        vibus = new VentanaInventarioBebidaUsuarioSimple();
        vibus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonBebidasInventarioActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "¿ Esta seguro que desea regresar al menú principal ?", "Mensaje",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            this.dispose();
            VentanaPrincipalSistemaUsuarioSimple vpsus;
            vpsus = new VentanaPrincipalSistemaUsuarioSimple();
            vpsus.setVisible(true);
        }
    }//GEN-LAST:event_botonRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBebidasInventario;
    private javax.swing.JButton botonIngredientesInventario;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
