/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaDePresentacion;

import capaDeNegocios.AdministrarBebidas;
import capaDeNegocios.AdministrarIngredientes;
import capaDeNegocios.IFacade;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Francisco
 */
public class VentanaAviso extends javax.swing.JFrame {

    IFacade facade = new IFacade();
    AdministrarIngredientes admin = new AdministrarIngredientes();
    AdministrarBebidas admon = new AdministrarBebidas();

    /**
     * Creates new form VentanaAvisoIngrediente
     */
    public VentanaAviso() {
        initComponents();
        mostrarAviso();
        mostrarAviso2();
        this.setLocationRelativeTo(null);
    }

    public void mostrarAviso() {
        DefaultTableModel dtm = new DefaultTableModel();
        this.tablaAviso1.setModel(dtm);
        ResultSet rs = null;
        dtm.setColumnIdentifiers(new Object[]{"NOMBRE", "EXISTENCIA EN GRAMOS"});
        facade.GetConnection();
        rs = admin.avisoIngredienteBajo();
        try {
            while (rs.next()) {

                dtm.addRow(new Object[]{rs.getString("nombre"), rs.getDouble("existencia")});
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaConsultasBebidas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void mostrarAviso2() {
        DefaultTableModel dtm = new DefaultTableModel();
        this.tablaAviso.setModel(dtm);
        ResultSet rs = null;
        dtm.setColumnIdentifiers(new Object[]{"NOMBRE", "EXISTENCIA EN GRAMOS"});
        facade.GetConnection();
        rs = admon.avisoBebidaBaja();
        try {
            while (rs.next()) {

                dtm.addRow(new Object[]{rs.getString("nombre"), rs.getDouble("existencia")});
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaConsultasBebidas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAviso = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAviso1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aviso Emergente");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("AVISO DE INVENTARIO: EXISTENCIA BAJA ");

        tablaAviso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Existencia"
            }
        ));
        jScrollPane1.setViewportView(tablaAviso);

        tablaAviso1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Existencia"
            }
        ));
        jScrollPane2.setViewportView(tablaAviso1);

        jLabel1.setText("Ingredientes:");

        jLabel3.setText("Bebidas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(156, 156, 156))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(botonAceptar)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaAviso;
    private javax.swing.JTable tablaAviso1;
    // End of variables declaration//GEN-END:variables
}
