/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaDePresentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author Francisco
 */
public class VentanaOpcionesReportes extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCompra
     */
    public VentanaOpcionesReportes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonReporteCompras = new javax.swing.JButton();
        botonReporteIngredientes = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        botonReporteVentas = new javax.swing.JButton();
        botonReporteBebidas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonReporteCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonReporteCompras.png"))); // NOI18N
        botonReporteCompras.setBorder(null);
        botonReporteCompras.setBorderPainted(false);
        botonReporteCompras.setContentAreaFilled(false);
        botonReporteCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonReporteCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteComprasActionPerformed(evt);
            }
        });
        getContentPane().add(botonReporteCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        botonReporteIngredientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonReporteIngredientes.png"))); // NOI18N
        botonReporteIngredientes.setBorder(null);
        botonReporteIngredientes.setBorderPainted(false);
        botonReporteIngredientes.setContentAreaFilled(false);
        botonReporteIngredientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonReporteIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteIngredientesActionPerformed(evt);
            }
        });
        getContentPane().add(botonReporteIngredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        botonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        botonRegresar.setBorder(null);
        botonRegresar.setBorderPainted(false);
        botonRegresar.setContentAreaFilled(false);
        botonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 60));

        botonReporteVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonReporteVentas.png"))); // NOI18N
        botonReporteVentas.setBorderPainted(false);
        botonReporteVentas.setContentAreaFilled(false);
        botonReporteVentas.setFocusable(false);
        botonReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteVentasActionPerformed(evt);
            }
        });
        getContentPane().add(botonReporteVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        botonReporteBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonReporteBebidas.png"))); // NOI18N
        botonReporteBebidas.setBorderPainted(false);
        botonReporteBebidas.setContentAreaFilled(false);
        botonReporteBebidas.setFocusable(false);
        botonReporteBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteBebidasActionPerformed(evt);
            }
        });
        getContentPane().add(botonReporteBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoOpcionInventario.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonReporteComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteComprasActionPerformed
        VentanaReporteCompras vrc;
        vrc = new VentanaReporteCompras();
        vrc.setVisible(true);
    }//GEN-LAST:event_botonReporteComprasActionPerformed

    private void botonReporteIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteIngredientesActionPerformed
        VentanaReporteIngrediente vri;
        vri = new VentanaReporteIngrediente();
        vri.setVisible(true);
    }//GEN-LAST:event_botonReporteIngredientesActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "¿ Esta seguro que desea regresar al menú principal ?", "Mensaje",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            this.dispose();
            VentanaPrincipalSistema vps;
            vps = new VentanaPrincipalSistema();
            vps.setVisible(true);

        }
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteVentasActionPerformed
        VentanaReporteVentas vrv;
        vrv = new VentanaReporteVentas();
        vrv.setVisible(true);
    }//GEN-LAST:event_botonReporteVentasActionPerformed

    private void botonReporteBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteBebidasActionPerformed
        VentanaReporteBebida vrb;
        vrb = new VentanaReporteBebida();
        vrb.setVisible(true);
    }//GEN-LAST:event_botonReporteBebidasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton botonReporteBebidas;
    private javax.swing.JButton botonReporteCompras;
    private javax.swing.JButton botonReporteIngredientes;
    private javax.swing.JButton botonReporteVentas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
