/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package capaDePresentacion;

import capaDeDatos.Bebida;
import capaDeNegocios.IFacade;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Z470
 */
public class VentanaVentaBebidas extends javax.swing.JFrame {
    
    Bebida bebida;
    ResultSet rs;
    VentanaVenta v;
    static double costo = 0;
//    AdministrarBebidas administrarBebidas = new AdministrarBebidas();
    IFacade facade = new IFacade();
    
    public VentanaVentaBebidas() throws SQLException {
        this.setLocationRelativeTo(null);
        initComponents();
        this.setLocationRelativeTo(null);
        
        rs = facade.SeleccionarBebidas();
        while (rs.next()) {
            this.comboBoxBebida.addItem(rs.getString("nombre"));
            
        }
        rs.close();
    }
    
    public void setBebida(Bebida bebida) {
        this.bebida = bebida;
        
    }
    
    public Bebida getBebida() {
        return bebida;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        comboBoxBebida = new javax.swing.JComboBox();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENTANA BEBIDAS");
        setPreferredSize(new java.awt.Dimension(445, 280));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboBoxBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxBebidaActionPerformed(evt);
            }
        });
        getContentPane().add(comboBoxBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 72, 288, 40));

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 173, 101, 36));

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 173, -1, 36));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Selecciona una Bebida:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 32, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoBebidas.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        
        this.dispose();

    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        String nombre = (String) comboBoxBebida.getSelectedItem();
        rs = facade.BuscarBebida(nombre);
        try {
            while (rs.next()) {
                this.bebida = new Bebida(rs.getInt("id_bebida"), rs.getString("nombre"), rs.getFloat("precio"), rs.getFloat("existencia"));
                
                setBebida(bebida);
                VentanaVenta.modelo.addElement(bebida);
                costo = bebida.getPrecio();
                VentanaVenta.costoVenta += costo;
                VentanaVenta.generarCosto();
                VentanaVenta.descripcion += "Bebida : " + bebida.getNombre() + ",\n";
                VentanaVenta.bebida = bebida;
                VentanaVenta.listaBeb.add(bebida);
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(VentanaVentaBebidas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.dispose();
        

    }//GEN-LAST:event_botonAceptarActionPerformed

    private void comboBoxBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxBebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxBebidaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JComboBox comboBoxBebida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
