/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaDePresentacion;

import capaDeNegocios.AdministrarCompras;
import capaDeNegocios.IFacade;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Francisco
 */
public class VentanaDetalleCompras extends javax.swing.JFrame {
    
    JTable tabla;
    ResultSet rs;
    JTable tabla2;
    IFacade facade = new IFacade();
    AdministrarCompras admincomp = new AdministrarCompras();

    /**
     * Creates new form VentanaDetalleCompraIngredientes
     */
    public VentanaDetalleCompras() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    private void validacionSoloNumeros(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        String txt = "-,+*¨{.}[]_!#$%&*/()=?¡áéíóú´|°¬;:";
        String caracter = String.valueOf(c);
        if (txt.contains(caracter)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Signo no permitido, Solo números");
        }
    }
    
    private void validacionSoloLetras(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        String txt = "-,+*¨{.}[]_!#$%&*/()=?¡áéíóú´|°¬;:";
        String caracter = String.valueOf(c);
        if (txt.contains(caracter)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Signo no permitido, letras");
        }
    }
    
    private void validacionNumeros(java.awt.event.KeyEvent evt) {
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se permiten números");
        }
    }
    
    private void validacionLetras(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se permiten letras");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentana = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaventanaBebidas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        textField = new javax.swing.JTextField();
        botonRegresarMenuPrincipal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENTANA DETALLE COMPRA");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Bebidas:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Ingredientes:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        botonConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonConsultarDetalles1png.png"))); // NOI18N
        botonConsultar.setBorderPainted(false);
        botonConsultar.setContentAreaFilled(false);
        botonConsultar.setFocusable(false);
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(botonConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 270, 110));

        tablaVentana.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_ingrediente", "nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVentana);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 676, 150));

        tablaventanaBebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_bebida", "nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaventanaBebidas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 676, 131));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Introduce el Id de la Compra:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        textField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textField.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActionPerformed(evt);
            }
        });
        textField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldKeyTyped(evt);
            }
        });
        getContentPane().add(textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 160, 40));

        botonRegresarMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back blue.png"))); // NOI18N
        botonRegresarMenuPrincipal.setBorder(null);
        botonRegresarMenuPrincipal.setBorderPainted(false);
        botonRegresarMenuPrincipal.setContentAreaFilled(false);
        botonRegresarMenuPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresarMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarMenuPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresarMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("TOTAL COMPRA: $");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, -1, -1));

        labelTotal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        getContentPane().add(labelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 170, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoDetalles.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActionPerformed
        String x = textField.getText();
        int id_Compra = Integer.parseInt(x);
        textField.setText("");
        DefaultTableModel dfm = new DefaultTableModel();
        DefaultTableModel dfm2 = new DefaultTableModel();
        tabla = this.tablaVentana;
        tabla.setModel(dfm);
        
        dfm.setColumnIdentifiers(new Object[]{"id_ingrediente", "nombre"});
        
        rs = admincomp.ingredientesCompra(id_Compra);
        try {
            while (rs.next()) {
                dfm.addRow(new Object[]{rs.getInt("id_ingrediente"), rs.getString("nombre")});
            }
            rs.close();
        } catch (Exception x2) {
            JOptionPane.showMessageDialog(null, "No se pueden obtener los resultados para la tabla");
        }
        
        tabla2 = this.tablaventanaBebidas;
        tabla2.setModel(dfm2);
        
        dfm2.setColumnIdentifiers(new Object[]{"id_bebida", "nombre"});
        rs = admincomp.bebidasCompra(id_Compra);
        
        try {
            while (rs.next()) {
                dfm2.addRow(new Object[]{rs.getInt("id_bebida"), rs.getString("nombre")});
            }
            rs.close();
        } catch (Exception x2) {
            JOptionPane.showMessageDialog(null, "No se pude obtener los resultados para la tabla");
        }
        rs = admincomp.CostoCompra(id_Compra);
        try {
            if (rs.next()) {
                Float f = rs.getFloat(1);
                String z = String.valueOf(f);
                labelTotal.setText(z);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaDetalleCompras.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_textFieldActionPerformed

    private void textFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldKeyTyped
        validacionNumeros(evt);
        validacionSoloNumeros(evt);
    }//GEN-LAST:event_textFieldKeyTyped

    private void botonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarActionPerformed
        textFieldActionPerformed(null);
    }//GEN-LAST:event_botonConsultarActionPerformed

    private void botonRegresarMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarMenuPrincipalActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "¿ Esta seguro que desea regresar ?", "Mensaje",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            this.dispose();
            VentanaOpcionesConsultarDetalles ventana;
            ventana = new VentanaOpcionesConsultarDetalles();
            ventana.setVisible(true);
        }
    }//GEN-LAST:event_botonRegresarMenuPrincipalActionPerformed
    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton botonRegresarMenuPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JTable tablaVentana;
    private javax.swing.JTable tablaventanaBebidas;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
