/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaDePresentacion;

import capaDeNegocios.AdministrarIngredientes;
import capaDeNegocios.IFacade;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Francisco
 */
public class VentanaReporteIngrediente extends javax.swing.JFrame {

    AdministrarIngredientes admin = new AdministrarIngredientes();
    IFacade facade = new IFacade();
    DateFormat format = new SimpleDateFormat("yyyy-MM--dd");
    JFormattedTextField dateTextField = new JFormattedTextField(format);

    /**
     * Creates new form VentanaReporteIngrediente
     */
    public VentanaReporteIngrediente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private void validacionSoloNumeros(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        String txt = "/,+*¨{.}[]_!#$%&*()=?¡áéíóú´|°¬;:asdfghjklqwertyuiopzxcvbnmñASDFGHJKLQWERTYUIOPZXCVBNMÑ";
        String caracter = String.valueOf(c);
        if (txt.contains(caracter)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Signo no permitido, Solo números");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        botonAceptar = new javax.swing.JButton();
        botonReporteVendidos = new javax.swing.JButton();
        botonReporteFechas = new javax.swing.JButton();
        campoFechaInicio = new javax.swing.JFormattedTextField();
        campoFechaFin = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENTANA REPORTE INGREDIENTES");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        botonAceptar.setBorderPainted(false);
        botonAceptar.setContentAreaFilled(false);
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 110, 60));

        botonReporteVendidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonReporteMasVendidos.png"))); // NOI18N
        botonReporteVendidos.setBorderPainted(false);
        botonReporteVendidos.setContentAreaFilled(false);
        botonReporteVendidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonReporteVendidos.setFocusable(false);
        botonReporteVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteVendidosActionPerformed(evt);
            }
        });
        getContentPane().add(botonReporteVendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 280, 120));

        botonReporteFechas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonReportePorFechas.png"))); // NOI18N
        botonReporteFechas.setToolTipText("");
        botonReporteFechas.setBorderPainted(false);
        botonReporteFechas.setContentAreaFilled(false);
        botonReporteFechas.setFocusable(false);
        botonReporteFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteFechasActionPerformed(evt);
            }
        });
        getContentPane().add(botonReporteFechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 250, 110));

        campoFechaInicio.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        try {
            campoFechaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoFechaInicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoFechaInicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        campoFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFechaInicioActionPerformed(evt);
            }
        });
        campoFechaInicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoFechaInicioKeyTyped(evt);
            }
        });
        getContentPane().add(campoFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 140, 31));

        campoFechaFin.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        try {
            campoFechaFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoFechaFin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoFechaFin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        campoFechaFin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoFechaFinKeyTyped(evt);
            }
        });
        getContentPane().add(campoFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 140, 31));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("FECHA DESDE:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("FECHA HASTA:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("año/mes/día");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 120, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("año/mes/día");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 100, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonReporteTotalVendidos.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 280, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoReportes.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        this.dispose();

    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonReporteFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteFechasActionPerformed
        if (campoFechaInicio.getText().trim().length() == 0 || campoFechaFin.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "VERIFIQUE NO EXISTAN CAMPOS VACIOS");
        } else {
            try {
                String ruta = "src/reportes/reportIng.jasper";
                Map parametros = new HashMap();
                parametros.put("FECHAINICIO", campoFechaInicio.getText());
                parametros.put("FECHAFIN", campoFechaFin.getText());
                JasperPrint reporte = JasperFillManager.fillReport(ruta, parametros, facade.GetConnection());
                JasperExportManager.exportReportToPdfFile(reporte, "src/reportes/reporteIng.pdf");
//            JasperViewer ventana = new JasperViewer(reporte, false);
//            ventana.setTitle("REPORTE DE INGREDIENTES");
//            ventana.setVisible(true);
//            JOptionPane.showMessageDialog(null, "Reporte Generado en formato PDF");
                try {
                    File path = new File("src/reportes/reporteIng.pdf");
                    Desktop.getDesktop().open(path);
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ingrese una Fecha de Inicio y una Fecha Hasta");
            }
        }
    }//GEN-LAST:event_botonReporteFechasActionPerformed

    private void botonReporteVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteVendidosActionPerformed

        try {
            String ruta = "src/reportes/ingredienteVendido.jasper";
            Map parametros = new HashMap();

            JasperPrint reporte = JasperFillManager.fillReport(ruta, parametros, facade.GetConnection());
            JasperExportManager.exportReportToPdfFile(reporte, "src/reportes/reporteIngredienteMasVendido.pdf");
            try {
                File path = new File("src/reportes/reporteIngredienteMasVendido.pdf");
                Desktop.getDesktop().open(path);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al generar el reporte");
        }

    }//GEN-LAST:event_botonReporteVendidosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String ruta = "src/reportes/reportIngTotales.jasper";
            Map parametros = new HashMap();

            JasperPrint reporte = JasperFillManager.fillReport(ruta, parametros, facade.GetConnection());
            JasperExportManager.exportReportToPdfFile(reporte, "src/reportes/reporteIngredientesVendidosTotales.pdf");
            try {
                File path = new File("src/reportes/reporteIngredientesVendidosTotales.pdf");
                Desktop.getDesktop().open(path);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al generar el reporte");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoFechaInicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoFechaInicioKeyTyped
        validacionSoloNumeros(evt);
    }//GEN-LAST:event_campoFechaInicioKeyTyped

    private void campoFechaFinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoFechaFinKeyTyped
        validacionSoloNumeros(evt);
    }//GEN-LAST:event_campoFechaFinKeyTyped

    private void campoFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFechaInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonReporteFechas;
    private javax.swing.JButton botonReporteVendidos;
    private javax.swing.JFormattedTextField campoFechaFin;
    private javax.swing.JFormattedTextField campoFechaInicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
