/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package capaDePresentacion;

import capaDeNegocios.IFacade;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Z470
 */
public class VentanaDetalleVentas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaDetalleVentas
     */
    JTable tabla;
    ResultSet rs;
    JTable tabla2;
    IFacade facade = new IFacade();

    public VentanaDetalleVentas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private void validacionSoloNumeros(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        String txt = "-,+*¨{.}[]_!#$%&*/()=?¡áéíóú´|°¬;:";
        String caracter = String.valueOf(c);
        if (txt.contains(caracter)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Signo no permitido, Solo números");
        }
    }

    private void validacionSoloLetras(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        String txt = "-,+*¨{.}[]_!#$%&*/()=?¡áéíóú´|°¬;:";
        String caracter = String.valueOf(c);
        if (txt.contains(caracter)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Signo no permitido, letras");
        }
    }

    private void validacionNumeros(java.awt.event.KeyEvent evt) {
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se permiten números");
        }
    }

    private void validacionLetras(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se permiten letras");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentana = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        textField = new javax.swing.JTextField();
        botonSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaventanaBebidas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        botonConsultar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENTANA DETALLE VENTAS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaVentana.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_ingrediente", "nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVentana);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 670, 139));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Introduce el Id de la Venta:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        textField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textField.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActionPerformed(evt);
            }
        });
        textField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldKeyTyped(evt);
            }
        });
        getContentPane().add(textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 110, 40));

        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back blue.png"))); // NOI18N
        botonSalir.setBorderPainted(false);
        botonSalir.setContentAreaFilled(false);
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.setFocusable(false);
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 110, 80));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Bebidas:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        tablaventanaBebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_bebida", "nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaventanaBebidas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 680, 114));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Ingredientes:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        botonConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonConsultarDetalles1png.png"))); // NOI18N
        botonConsultar.setBorderPainted(false);
        botonConsultar.setContentAreaFilled(false);
        botonConsultar.setFocusable(false);
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(botonConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 282, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoDetalles.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActionPerformed
        String x = textField.getText();
        int id_Venta = Integer.parseInt(x);
        textField.setText("");
        DefaultTableModel dfm = new DefaultTableModel();
        DefaultTableModel dfm2 = new DefaultTableModel();
        tabla = this.tablaVentana;
        tabla.setModel(dfm);

        dfm.setColumnIdentifiers(new Object[]{"id_ingrediente", "nombre"});

        rs = facade.ingredientesVenta(id_Venta);
        try {
            while (rs.next()) {
                dfm.addRow(new Object[]{rs.getInt("id_ingrediente"), rs.getString("nombre")});
            }
            rs.close();
        } catch (Exception x2) {
            JOptionPane.showMessageDialog(null, "No se pueden obtener los resultados para la tabla");
        }

        tabla2 = this.tablaventanaBebidas;
        tabla2.setModel(dfm2);

        dfm2.setColumnIdentifiers(new Object[]{"id_bebida", "nombre"});
        rs = facade.bebidasVenta(id_Venta);

        try {
            while (rs.next()) {
                dfm2.addRow(new Object[]{rs.getInt("id_bebida"), rs.getString("nombre")});
            }
            rs.close();
        } catch (Exception x2) {
            JOptionPane.showMessageDialog(null, "No se pude obtener los resultados para la tabla");
        }


    }//GEN-LAST:event_textFieldActionPerformed

    private void textFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldKeyTyped
        validacionNumeros(evt);
        validacionSoloNumeros(evt);

    }//GEN-LAST:event_textFieldKeyTyped

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "¿ Esta seguro que desea regresar ?", "Mensaje",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            this.dispose();
            VentanaOpcionesConsultarDetalles ventana;
            ventana = new VentanaOpcionesConsultarDetalles();
            ventana.setVisible(true);
        }
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarActionPerformed
        textFieldActionPerformed(null);
    }//GEN-LAST:event_botonConsultarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaVentana;
    private javax.swing.JTable tablaventanaBebidas;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
